<?php

/**
 *
 * ZEND GROUP
 *
 * @name        WorkflowReplationship.php
 * @category    ZG
 * @package     Model
 * @subpackage  Model\Repositories
 * @author      Thuy Dinh Xuan <thuydx@zendgroup.vn>
 * @link         http://zendgroup.vn
 * @copyright   Copyright (c) 2012-2013 ZEND GROUP. All rights reserved (http://www.zendgroup.vn)
 * @license     http://zendgroup.vn/license/
 * @version     $0.1$
 *
 * LICENSE
 *
 * This source file is copyrighted by ZEND GROUP, full details in LICENSE.txt.
 * It is also available through the Internet at this URL:
 * http://zendgroup.vn/license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the Internet, please send an email
 * to license@zendgroup.vn so we can send you a copy immediately.
 */

namespace Workflow\Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * WorkflowReplationship
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowReplationship extends EntityRepository
{
}
